# app.py
import streamlit as st
import requests
from content import LANDING_TEXT, PRODUCT_INFO, PRICING_TIERS
from styles import get_external_css

# 1. PAGE CONFIGURATION
st.set_page_config(
    page_title="EarnedEdge | Project Controls", 
    page_icon="📈", 
    layout="wide",
    initial_sidebar_state="collapsed"
)

# 2. INJECT CSS
st.markdown(get_external_css(), unsafe_allow_html=True)

# 3. NAVIGATION (TABS)
tabs = st.tabs(["Home", "Solution", "Pricing", "Booking", "Contact"])

# --- TAB 1: HOME ---
with tabs[0]:
    # Hero Banner
    st.markdown(f"""
        <div class="hero-banner">
            <h1 style='font-size: 3.5rem; margin-bottom: 1rem; color: #000;'>{LANDING_TEXT['hero_title']}</h1>
            <p style='font-size: 1.5rem; color: #555; font-weight: 300;'>{LANDING_TEXT['hero_subtitle']}</p>
            <div style='margin-top: 2rem;'>
                <h2 style='color: #0070F2; font-size: 2rem;'>{LANDING_TEXT['hero_tagline']}</h2>
                <p style='max-width: 800px;'>{LANDING_TEXT['hero_description']}</p>
            </div>
        </div>
    """, unsafe_allow_html=True)
    
    # Value Props
    st.markdown("<br>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns(3)
    
    with c1:
        st.markdown("""
        <div class="sap-card">
            <h3 style="color: #0070F2;">Compliance-First</h3>
            <p>ISO 9001 & UK GDPR compliant audit trails built for Tier 1 scrutiny.</p>
        </div>
        """, unsafe_allow_html=True)
        
    with c2:
        st.markdown("""
        <div class="sap-card">
            <h3 style="color: #0070F2;">AI-Powered Insight</h3>
            <p>Narrative board packs generated by Claude, verified by human analysts.</p>
        </div>
        """, unsafe_allow_html=True)
        
    with c3:
        st.markdown("""
        <div class="sap-card">
            <h3 style="color: #0070F2;">Fixed Retainer</h3>
            <p>Predictable monthly pricing. No hidden costs or daily rates.</p>
        </div>
        """, unsafe_allow_html=True)

# --- TAB 2: PRODUCT ---
with tabs[1]:
    st.markdown("<div style='padding: 2rem 0;'>", unsafe_allow_html=True)
    st.header("The System: ControlsDesk Architecture")
    st.write("A seamless integration of data science and project governance.")
    st.markdown("</div>", unsafe_allow_html=True)
    
    col_left, col_right = st.columns([1, 1], gap="large")
    
    with col_left:
        st.subheader("The Process")
        for item in PRODUCT_INFO['how_it_works']:
            st.markdown(f"""
            <div style="display:flex; align-items: flex-start; margin-bottom: 1rem;">
                <span style="color:#0070F2; margin-right: 10px; font-weight:bold;">➤</span>
                <span>{item}</span>
            </div>
            """, unsafe_allow_html=True)
            
    with col_right:
        st.subheader("Key Deliverables")
        for item in PRODUCT_INFO['deliverables']:
             st.markdown(f"""
            <div style="background-color: #F5F7F9; padding: 1rem; border-left: 4px solid #107E3E; margin-bottom: 0.8rem;">
                <span style="font-weight:600;">{item}</span>
            </div>
            """, unsafe_allow_html=True)

# --- TAB 3: PRICING ---
with tabs[2]:
    st.markdown("<div style='padding: 2rem 0;'>", unsafe_allow_html=True)
    st.header("Transparent Pricing")
    st.write("Enterprise capabilities scaled for the SME budget.")
    st.markdown("</div>", unsafe_allow_html=True)
    
    cols = st.columns(len(PRICING_TIERS), gap="medium")
    
    for i, (name, data) in enumerate(PRICING_TIERS.items()):
        with cols[i]:
            # Feature list HTML
            features_html = "".join([f"<li style='margin-bottom: 0.5rem;'>{f}</li>" for f in data['features']])
            
            st.markdown(f"""
                <div class="sap-card" style="border-top: 6px solid {data['color']}; text-align: left;">
                    <h3 style="color: {data['color']}; margin-top:0;">{name}</h3>
                    <h2 style="font-size: 2.5rem; color: #32363A;">{data['price']}<span style='font-size:1rem; color: #666;'>/mo</span></h2>
                    <ul style="padding-left: 1.2rem; margin-top: 1.5rem; color: #555;">
                        {features_html}
                    </ul>
                </div>
            """, unsafe_allow_html=True)
            
            st.markdown("<br>", unsafe_allow_html=True)
            if st.button(f"Select {name}", key=f"btn_{name}"):
                st.info("Redirecting to secure onboarding...")

# --- TAB 4: BOOKING ---
with tabs[3]:
    # Clean layout: No wrapper divs, just Streamlit flow
    col_a, col_b = st.columns([2, 1])
    
    with col_a:
        st.header("Schedule a Consultation")
        st.write("Book a 30-minute discovery call to discuss your reporting requirements.")
        st.write("Our team will review your current WBS and reporting gaps.")
        
        st.markdown("<br>", unsafe_allow_html=True)
        st.link_button("📅 Open Calendar", "https://calendar.google.com/calendar/appointments/schedules/")
        st.caption("Includes automated Google Meet link.")

# --- TAB 5: CONTACT ---
with tabs[4]:
    st.header("Contact Us")
    st.write("Have a specific question about SAP/Oracle integration?")
    
    # Form Container
    with st.container():
        col_form, col_spacer = st.columns([2, 1])
        with col_form:
            with st.form("contact"):
                name = st.text_input("Full Name")
                email = st.text_input("Business Email")
                message = st.text_area("How can we help?")
                
                submitted = st.form_submit_button("Send Message")
                
                if submitted:
                    if not name or not email:
                        st.error("Please fill in your name and email.")
                    else:
                        slack_data = {
                            "text": f"🚨 **New Lead:** {name}\n📧 **Email:** {email}\n📝 **Message:** {message}"
                        }
                        try:
                            if "SLACK_WEBHOOK_URL" in st.secrets:
                                response = requests.post(st.secrets["SLACK_WEBHOOK_URL"], json=slack_data)
                                if response.status_code == 200:
                                    st.success("Message sent! We'll be in touch shortly.")
                                else:
                                    st.error("System error. Please email us directly.")
                            else:
                                st.warning("Dev Mode: Slack Secret not found. Message not sent.")
                        except Exception as e:
                            st.error(f"Connection error: {e}")

# FOOTER
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center; color: #666; font-size: 0.8rem; padding: 2rem;'>
        © 2026 EarnedEdge. ISO 9001 Compliant Procedures. Built for West Midlands Infrastructure.<br>
        <span style='color: #888;'>SAP® is a registered trademark of SAP SE. EarnedEdge is an independent provider.</span>
    </div>
    """, 
    unsafe_allow_html=True
)
