# app.py
import streamlit as st
import requests
from content import LANDING_TEXT, PRODUCT_INFO, PRICING_TIERS
from styles import get_external_css

# 1. PAGE CONFIGURATION
st.set_page_config(
    page_title="EarnedEdge | Project Controls", 
    page_icon="📈", 
    layout="wide",
    initial_sidebar_state="collapsed"
)

# 2. INJECT CSS
st.markdown(get_external_css(), unsafe_allow_html=True)

# 3. NAVIGATION (TABS)
tabs = st.tabs(["🏠 Home", "🛠 Product", "💰 Pricing", "📅 Booking", "📩 Contact"])

# --- TAB 1: HOME ---
with tabs[0]:
    st.markdown(f"""
        <div class="hero-box">
            <h1 style='font-size: 3rem; margin-bottom: 0.5rem;'>{LANDING_TEXT['hero_title']}</h1>
            <p style='font-size: 1.5rem; color: #333; font-weight: 500;'>{LANDING_TEXT['hero_subtitle']}</p>
            <hr style='border: 1px solid #ddd; margin: 1.5rem 0;'>
            <h2 style='color: #0070F2;'>{LANDING_TEXT['hero_tagline']}</h2>
            <p style='font-size: 1.1rem;'>{LANDING_TEXT['hero_description']}</p>
        </div>
    """, unsafe_allow_html=True)
    
    # Value Props (Using standard Streamlit columns, styled by CSS)
    c1, c2, c3 = st.columns(3)
    with c1:
        st.info("**Compliance-First**\n\nISO 9001 & UK GDPR compliant audit trails.")
    with c2:
        st.success("**AI-Powered Insight**\n\nNarrative board packs generated by Claude.")
    with c3:
        st.warning("**Fixed Retainer**\n\nPredictable monthly pricing. No hidden costs.")

# --- TAB 2: PRODUCT ---
with tabs[1]:
    st.markdown("<div style='background-color: white; padding: 2rem; border-radius: 10px; box-shadow: 0 2px 5px rgba(0,0,0,0.05);'>", unsafe_allow_html=True)
    st.header("The System: ControlsDesk Architecture")
    col_left, col_right = st.columns(2)
    
    with col_left:
        st.subheader("Process")
        for item in PRODUCT_INFO['how_it_works']:
            st.markdown(f"- {item}")
            
    with col_right:
        st.subheader("Deliverables")
        for item in PRODUCT_INFO['deliverables']:
            st.success(f"✅ {item}")
    st.markdown("</div>", unsafe_allow_html=True)

# --- TAB 3: PRICING ---
with tabs[2]:
    st.header("Transparent Pricing")
    cols = st.columns(len(PRICING_TIERS))
    
    for i, (name, data) in enumerate(PRICING_TIERS.items()):
        with cols[i]:
            # Generate HTML for features list
            features_html = "".join([f"<p style='margin: 5px 0; border-bottom: 1px solid #eee; padding-bottom: 5px;'>{f}</p>" for f in data['features']])
            
            st.markdown(f"""
                <div class="pricing-card" style="border-top: 5px solid {data['color']};">
                    <h3 style="color: {data['color']}; font-weight: 800;">{name}</h3>
                    <h2 style="font-size: 2.5rem; margin: 10px 0;">{data['price']}<span style='font-size:1rem; color: #666;'>/mo</span></h2>
                    <hr>
                    <div style='text-align: left; margin-top: 1rem;'>
                        {features_html}
                    </div>
                </div>
            """, unsafe_allow_html=True)
            
            # Spacer for button alignment
            st.markdown("<br>", unsafe_allow_html=True)
            if st.button(f"Choose {name}", key=f"btn_{name}"):
                st.info("Redirecting to secure onboarding...")

# --- TAB 4: BOOKING ---
with tabs[3]:
    st.markdown("<div class='hero-box'>", unsafe_allow_html=True)
    st.header("Schedule a Consultation")
    st.write("Book a 30-minute discovery call via Google Meet.")
    
    # Calendar Button
    st.link_button("📅 Open Calendar", "https://calendar.google.com/calendar/appointments/schedules/")
    st.caption("Includes automated Google Meet link.")
    st.markdown("</div>", unsafe_allow_html=True)

# --- TAB 5: CONTACT ---
with tabs[4]:
    st.markdown("<div class='hero-box'>", unsafe_allow_html=True)
    st.header("Contact Us")
    with st.form("contact"):
        name = st.text_input("Name")
        email = st.text_input("Email")
        message = st.text_area("Message")
        
        submitted = st.form_submit_button("Send to EarnedEdge")
        
        if submitted:
            if not name or not email:
                st.error("Please fill in your name and email.")
            else:
                # Prepare payload
                slack_data = {
                    "text": f"🚨 **New Lead:** {name}\n📧 **Email:** {email}\n📝 **Message:** {message}"
                }
                
                # Send to Slack (Requires 'secrets.toml' locally or Secrets in Cloud)
                try:
                    # Check if secret exists to prevent crash in dev
                    if "SLACK_WEBHOOK_URL" in st.secrets:
                        response = requests.post(st.secrets["SLACK_WEBHOOK_URL"], json=slack_data)
                        if response.status_code == 200:
                            st.success("Message sent! We'll be in touch shortly.")
                            st.balloons()
                        else:
                            st.error("System error. Please email us directly.")
                    else:
                        st.warning("Dev Mode: Slack Secret not found. Message not sent.")
                except Exception as e:
                    st.error(f"Connection error: {e}")
    st.markdown("</div>", unsafe_allow_html=True)

# FOOTER
st.markdown("---")
st.markdown(
    "<div style='text-align: center; color: #666;'>"
    "© 2026 EarnedEdge. ISO 9001 Compliant Procedures. Built for West Midlands Infrastructure."
    "</div>", 
    unsafe_allow_html=True
)
